#!/usr/bin/env -S npx tsx
/**
 * The Phase 1 STT accuracy spike (docs/ARCHITECTURE.md §15/§16).
 *
 * There is no published benchmark for STT accuracy on programming jargon - Deepgram's own
 * keyterm evidence is *confidence* gains on medical vocabulary, not accuracy on code terms. This
 * script exists to produce a real number before any later phase trusts a transcript for scoring.
 *
 * Never wired into the app. A standalone CLI, run by hand against real recorded clips:
 *
 *   npm run stt-spike -- clip.webm reference.txt
 *
 * `clip.webm` is any short recording of you explaining a coding approach out loud - record it
 * with whatever is convenient (a phone voice memo app exported as audio works, though webm/opus
 * from a browser is the closest match to what the app itself will send).
 *
 * `reference.txt` is what you actually said, typed out by hand. This is the ground truth WER is
 * measured against - it is not optional and it is not generated by the tool itself, since the
 * whole point is comparing STT output to what a human knows was said.
 *
 * Run this once per clip for ~10 clips, per docs/ARCHITECTURE.md §15, and write the resulting
 * word error rates - raw vs. keyterm-boosted - into that document by hand.
 */

import { readFile } from "node:fs/promises";
import path from "node:path";

import { STT_KEYTERMS } from "../src/lib/stt/keyterms";
import { transcribe } from "../src/lib/stt/transcribe";
import { wordErrorRate } from "../src/lib/stt/wer";

async function loadEnvIfPresent(): Promise<void> {
  // Next.js loads .env.local automatically for `next dev`/`next build`; a standalone script run
  // via `tsx` does not get that for free, so do it explicitly. Node 20.6+ ships this natively -
  // no dotenv dependency needed for one call.
  try {
    process.loadEnvFile(path.resolve(process.cwd(), ".env.local"));
  } catch {
    // No .env.local - fine if the keys are already in the environment some other way.
  }
}

function formatPercent(fraction: number): string {
  return `${(fraction * 100).toFixed(1)}%`;
}

async function main(): Promise<void> {
  const [clipPath, referencePath] = process.argv.slice(2);

  if (!clipPath || !referencePath) {
    console.error("Usage: npm run stt-spike -- <clip.webm> <reference.txt>");
    process.exitCode = 1;
    return;
  }

  await loadEnvIfPresent();

  if (!process.env.DEEPGRAM_API_KEY) {
    console.error("DEEPGRAM_API_KEY is not set. Add it to .env.local first.");
    process.exitCode = 1;
    return;
  }

  const audio = await readFile(path.resolve(clipPath));
  const reference = (await readFile(path.resolve(referencePath), "utf-8")).trim();
  const filename = path.basename(clipPath);

  console.log(`Clip:      ${clipPath} (${(audio.length / 1024).toFixed(0)} KB)`);
  console.log(`Reference: ${reference}`);
  console.log();

  const [raw, boosted] = await Promise.all([
    transcribe(audio, filename),
    transcribe(audio, filename, { keyterms: STT_KEYTERMS }),
  ]);

  const rawWer = wordErrorRate(reference, raw.text);
  const boostedWer = wordErrorRate(reference, boosted.text);

  console.log("Raw (no keyterms):");
  console.log(`  Transcript: ${raw.text}`);
  console.log(`  Confidence: ${formatPercent(raw.confidence)}`);
  console.log(
    `  WER:        ${formatPercent(rawWer.wer)} ` +
      `(${rawWer.substitutions} sub, ${rawWer.deletions} del, ${rawWer.insertions} ins ` +
      `/ ${rawWer.referenceWordCount} ref words)`,
  );
  console.log();

  console.log("Keyterm-boosted:");
  console.log(`  Transcript: ${boosted.text}`);
  console.log(`  Confidence: ${formatPercent(boosted.confidence)}`);
  console.log(
    `  WER:        ${formatPercent(boostedWer.wer)} ` +
      `(${boostedWer.substitutions} sub, ${boostedWer.deletions} del, ${boostedWer.insertions} ins ` +
      `/ ${boostedWer.referenceWordCount} ref words)`,
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
